version: '3.8'
services:
  mysql-db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: transactiondb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
    ports:
      - '3307:3306'
    volumes:
      - mysql-backup:/var/lib/mysql

  application:
    build:
      context: .
      dockerfile: Dockerfile
    image: transaction-service:1.0
    depends_on:
      mysql-db:
        condition: service_healthy

    ports:
      - '9090:8181'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql-db:3306/transactiondb'
      SPRING_DATASOURCE:USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  mysql-backup: